name: Build
on:
  push:
    branches: 
      - master
      - release/*
      - build-2
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]
        python: [ 3.7]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
     
      - name: Build Application Windows
        if: runner.os == 'Windows'
        run: |
          python -m venv mainbuild
          mainbuild\Scripts\activate
          pip install -r requirements.txt
          pip install pyinstaller
          pyinstaller --onefile --noconfirm --nowindow --add-data="Fonts\*;Fonts" --add-data="Images\*;Images" --add-data="Sounds\*;Sounds" --add-data="help.doghelp;." main-pygame.py
      - name: Build Application Non Windows
        if: runner.os != 'Windows'
        run: |
          mkdir dist
          pip install -r requirements.txt
          pip install pyinstaller
          pyinstaller --onefile --noconfirm --nowindow --add-data="Fonts/*:Fonts" --add-data="Images/*:Images" --add-data="Sounds/*:Sounds" --add-data="help.doghelp:." main-pygame.py
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}
          path: dist/*

          
